# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import portals.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('id_no', models.IntegerField(blank=True, help_text='Your National ID Number', null=True)),
                ('email', models.EmailField(default='parent@example.com', max_length=254)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('residence', models.CharField(default='Kaborom', max_length=100)),
                ('profession', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=portals.models.upload_location, width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='About this rank ...')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_no', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('id_no', models.IntegerField(blank=True, help_text='Your National ID Number', null=True)),
                ('email', models.EmailField(default='staff@example.com', max_length=254)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('residence', models.CharField(default='Kaborom', max_length=100)),
                ('level_of_study', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=portals.models.upload_location, width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rank', models.ManyToManyField(blank=True, to='portals.Rank')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('reg_no', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('residence', models.CharField(default='Kaborom', max_length=100)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=portals.models.upload_location, width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('parent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portals.Parent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
