# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0002_auto_20170315_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='user',
            new_name='user_acc',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='user_acc',
        ),
    ]
