# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0003_auto_20170315_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-year_of_study', '-timestamp']},
        ),
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='id_no',
            field=models.IntegerField(blank=True, help_text='Your National ID Number', null=True, unique=True),
        ),
    ]
