# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 16:40
from __future__ import unicode_literals

import academics.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccademicEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EndTermExamPerformance',
            fields=[
                ('reg_no', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('mathematics', models.IntegerField(blank=True, null=True)),
                ('english', models.IntegerField(blank=True, null=True)),
                ('kiswahili', models.IntegerField(blank=True, null=True)),
                ('science', models.IntegerField(blank=True, null=True)),
                ('sst_cre', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tch_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=academics.models.upload_location, width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('time', models.TimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Day')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Teacher')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Time')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('students', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=academics.models.upload_location, width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='timetable',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Year'),
        ),
    ]
